### ISSUE TITLE
About gI definition during VIO initialization

### ISSUE THREAD

**Issue by HeatherHu** [jingpang/LearnVIORB#10]
In your code the gravity vector is set as 
     gI.at<float>(2) = 1;
here is different from the paper(says -1). Is this correct? Also do you know what G in every equation means in the paper. I found you just ignore this item.
Thanks.

**Comment by jingpang** [comment]
Either 1 or -1 is OK, if you keep it in mind for all other usage in the code. (I use NED frame definition, so i think in this frame the gravity is [0;0;9.8]). If you use -1, it's also OK and only minor modifications are required.

**Comment by HeatherHu** [comment]
Thanks very much.
