### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by jamestodo** [jingpang/LearnVIORB#12]
In IMUPreintegrator.h,the function `JacobianR` calculates the right jacobian by the formula 
`JR = I - (1- cos( theta ) ) / theta * K + ( 1 - sin( theta ) / theta ) * K * K`.But i saw the formula to do the same thing in Gao Xiang's blog was `JR = sin( theta ) / theta * I - (1- cos( theta ) ) / theta * K + ( 1 - sin( theta ) / theta ) * k * k.transpose()`.I wonder if i was wrong or misunderstood somewhere.

**Comment by jingpang** [comment]
It's the same. As 
k * k.transpose = k^ * k^ + (k.transpose * k) *I

Refer to 'SO(3) identities and approximations' in about pg244 of the book 'State Estimation for Robotics' by Barfoot.

You can also find the formula of the right Jacobian in the book.

**Comment by jamestodo** [comment]
Sorry,i haven't found the formula  about `k * k.transpose = k^ * k^ + (k.transpose * k) *I` in the page range 231-246 of the book you mentioned.But with that formula,they are just the same.

**Comment by jingpang** [comment]
The equation can be found [here](http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17_identities.pdf).
The 7th equation in the column 'Lie Algebra'.

**Comment by jamestodo** [comment]
I've found that with your help.Thanks a lot!

**Comment by jamestodo** [comment]
In function `IMUPreintegrator::update()`,how to calculate the variable `_cov_P_V_Phi`,`_J_(P/V/R)_Bias(g/a)`.I wonder to know the reference of them.And i found the reference of the variable `_delta_(P/V/R)`'s  on paper `On-Manifold Preintegration for Real-Time
Visual-Inertial Odometry`.But  the `_J_(P/V/R)_Bias(g/a)` has a little difference with the paper i mentioned.

**Comment by jingpang** [comment]
It's the same as Appendix.B in the paper you mentioned.
But in the code it's implemented as J(i+1) = J(i) + J_add, which can be easily derived from the equation.

**Comment by jamestodo** [comment]
In the paper,the `_J_R_Biasg = dR.transpose()*_J_R_Biasg * Jr*dt`.But in your code,it was 
`_J_R_Biasg = dR.transpose()*_J_R_Biasg - Jr*dt`.

And i found the noise covariance propagation of delta measurements in the Appendix.E.But i couldn't correlate these part with your code about `_cov_P_V_Phi`.

**Comment by xukuanHIT** [comment]
@zdczdcc 
Hi， I hope it can help you
![1248330106](https://user-images.githubusercontent.com/17938325/33791481-1fedf22c-dcc7-11e7-88a4-e62052f52613.jpg)

**Comment by jamestodo** [comment]
@xukuanHIT ,
I've understood it with your help.Thanks a lot!

**Comment by lianbin** [comment]
> @zdczdcc
> Hi， I hope it can help you
> ![1248330106](https://user-images.githubusercontent.com/17938325/33791481-1fedf22c-dcc7-11e7-88a4-e62052f52613.jpg)

  But ,in the code ,why compute delta Ri j+1 / deltabg   but  not  delta Ri j / deltabg as the paper?  Thank you.
@jingpang @xukuanHIT
