### ISSUE TITLE
Building issue: "Could NOT find CHOLMOD"

### ISSUE THREAD

**Issue by marco-tranzatto** [jingpang/LearnVIORB#13]
Hi,

Thanks for sharing this repo!
I'm trying to test it, but when I execute the `build.sh` script I get the following error:
```
Could NOT find CHOLMOD (missing:  CHOLMOD_INCLUDE_DIR CHOLMOD_LIBRARIES) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CHOLMOD_INCLUDE_DIR
   used as include directory in directory /home/marco/viorb_ws/src/LearnVIORB
CHOLMOD_LIBRARY
    linked by target "ORB_SLAM2" in directory /home/marco/viorb_ws/src/LearnVIORB

-- Configuring incomplete, errors occurred!
```

Any idea why?

Thanks,
Marco.

**Comment by jingpang** [comment]
Maybe you need to install cholmod by 'sudo apt-get install libsuitesparse-dev'.

**Comment by marco-tranzatto** [comment]
thanks! :+1:

**Comment by connorsoohoo** [comment]
I also got the same build error. Installing CHOLMOD alone didn't fix this issue for me. What I had to do was specify the full path of "cholmod.h" in g2o's "linear_solver_cholmod.h" file. Mine happened to be in /usr/include/suitesparse/
