### ISSUE TITLE
Loop closing not working?

### ISSUE THREAD

**Issue by yan-lu** [jingpang/LearnVIORB#14]
On the same data, ORB_SLAM2 is able to detect the loop and correct the map, but VIORB does not. Seems strange. Any clues?

**Comment by jingpang** [comment]
First, loop closing in the real-time version may be not so stable and I didn't figure out why..

Another cause may be the (scale) error. The LoopClosing is set to ignore the scale error [here in System.cc](https://github.com/jingpang/LearnVIORB/blob/RT/src/System.cc#L219). So the recall of loop closure may be lower than ORB-SLAM2, especially for difficult data with some large accumulated error.

Which bags of EuRoc did you fail to close the loop?
