### ISSUE TITLE
Reinitialization problem

### ISSUE THREAD

**Issue by imrasp** [jingpang/LearnVIORB#17]
I have try your version in RT branch and connect it to mavlink to get imu from pixhawk and using image from monocular camera. the problem is after reinitialization complete the previous generated point cloud never come back as a part of new initialization. Is this part already implemented? and what can cause this problem?

**Comment by jingpang** [comment]
I didn't take re-initialization into account. When the system resets, the previous map is cleared.

Some more modifications are required to implement the re-initialization with previous map, and I've not implemented that.
