### ISSUE TITLE
pKFi->mvuRight[mit->second]<0

### ISSUE THREAD

**Issue by wangminhang** [jingpang/LearnVIORB#18]
In Optimizer.cc, why pKFi->mvuRight[mit->second]<0 could decide sensor is stereo or Monocular？
if I use RGBD, where should i modified?

**Comment by jingpang** [comment]
Hi, this issue should be opened in ORB_SLAM2.
BTW, I only implemented monocular Visual-Inertial SLAM, so mvuRight[] is not used in the code.
