### ISSUE TITLE
feature lost when after TryInitVIO return true

### ISSUE THREAD

**Issue by wangminhang** [jingpang/LearnVIORB#19]
I run this program in realtime with RealSense Camaro，when the function LocalMapping::TryInitVIO() returns true , all features lost and can't be catched. 
How to solve this issue? Thank you！

Also in this function，sometimes the scale and depth is negative，why？

**Comment by jingpang** [comment]
Perhaps the image and imu messages are not well synchronized, so the initialization may get wrong result.

**Comment by Veerachart** [comment]
@wangminhang has you happened to get some solution to this?

I also got some similar problem, with scale values sometime positive sometime negative. If I am lucky, then positive value is obtained, but the tracking seems not working so well and I don't think the scale is correct. Most of the time I end up losing the track.
