### ISSUE TITLE
No image input

### ISSUE THREAD

**Issue by JHzss** [jingpang/LearnVIORB#24]
Hi,
Thanks for your work! But when I roslaunch ORB_VIO testeuroc.launch, why there is no image input? I have already modified the the path in config/euroc.yaml and build the project successfully.

**Comment by guilhermelawless** [comment]
If you have realtime = 1 you need to provide the images and IMU readings from a rosbag.

**Comment by JHzss** [comment]
Thank you very much, but I don't know why when I have realtime = 0, it works.What's more, I provide  a rosbag for it. @guilhermelawless

**Comment by JHzss** [comment]
oh, I know, thank you!
