### ISSUE TITLE
Is it possible to replace g2o with ceres as the backend and will it be faster or have better accuracy?

### ISSUE THREAD

**Issue by highlightz** [jingpang/LearnVIORB#25]
I notice that there are some jobs taking ceres as the backend optimization framework, such as OKVIS and HKUST-Mono. Here in your code, g2o is used. I have always wondered between g2o and ceres, which may behaves better. So can I know the reason why g2o is used in your implementation? And Is it possible to replace g2o with ceres as the backend and will it be faster or have better accuracy?

**Comment by jingpang** [comment]
The reason I use g2o is that this project is based on ORB_SLAM which uses g2o. Of course you can replace g2o with ceres. But I have not compared them so I don't know the performance.
