### ISSUE TITLE
A problem about the update of Map scale after running TryInitVIO()

### ISSUE THREAD

**Issue by TAO270** [jingpang/LearnVIORB#41]
Hi.
Here in the functionTryInitVIO(), the system had uptaded the map scales including all mappoints and keyframs, but in the next program, the map scales would be updated again.
What's the difference between these two updates?

                bool tmpbool = TryInitVIO();
                        SetVINSInited(tmpbool);
                        if(tmpbool)
                        {
                            // Update map scale
                           mpMap->UpdateScale(mnVINSInitScale);
                            // Set initialization flag
                            SetFirstVINSInited(true);
                        }

Thank you in advance.

**Comment by highlightz** [comment]
There are two different conditions. The `TryInitVIO` in VINSInitThread is for real-time running, your above-mentioned snippets are for non-realtime running.    
Pay attention to `ConfigParam::GetRealTimeFlag()`, you'll understand this.

**Comment by TAO270** [comment]
@highlightz 
Thanks for your response. 
I did notice that there are two different conditions for  real-time and non real-time running. In config file, the flag has been set to zero for non-realtime. Therefore, the system does not call the thread 

ORB_SLAM2::LocalMapping::VINSInitThread

because that thread just  runs when the realtime flag is non-zero.

In two different situations, the system will call this thread (in System.cc about line 270)

 mptLocalMapping = new thread(&ORB_SLAM2::LocalMapping::Run,mpLocalMapper);

I guess function LocalMapping::Run() executes TryInitVIO(), and TryInitVIO() implements the update of map scale. Is that all right? some snippets in TryInitVIO() are 

           // Update poses (multiply metric scale)
            vector<KeyFrame*> mspKeyFrames = mpMap->GetAllKeyFrames();
            for(std::vector<KeyFrame*>::iterator sit=mspKeyFrames.begin(), send=mspKeyFrames.end(); sit!=send; sit++)
            {
                KeyFrame* pKF = *sit;
                cv::Mat Tcw = pKF->GetPose();
                cv::Mat tcw = Tcw.rowRange(0,3).col(3)*scale;
                tcw.copyTo(Tcw.rowRange(0,3).col(3));
                pKF->SetPose(Tcw);
            }

            vector<MapPoint*> mspMapPoints = mpMap->GetAllMapPoints();
            for(std::vector<MapPoint*>::iterator sit=mspMapPoints.begin(), send=mspMapPoints.end(); sit!=send; sit++)
            {
                MapPoint* pMP = *sit;
                //pMP->SetWorldPos(pMP->GetWorldPos()*scale);
                pMP->UpdateScale(scale);
            }
            std::cout<<std::endl<<"... Map scale updated ..."<<std::endl<<std::endl;

And then, the previously mentioned snippets would execute the action of update again, because the flag is zero.

**Comment by TAO270** [comment]
Actually, I would like to express that the map scale is updated when running TryInitVIO(), and then mpMap->UpdateScale(mnVINSInitScale) would update that again.

**Comment by ns15417** [comment]
@Markbess have you solved this question cuz you closed it. I am also confused why the map is updated twice cuz if it is set to non-realtime mode, the update will be executed both inside TryInitVIO() and LocalMapping::Run(). This leads to some keyframe drifts away when the second update is finished while it is totally ok if i note the second update.
How did you solve this problem ?
